name: Create Azure VM

permissions:
    id-token: write
    contents: read
on:
    workflow_dispatch:
jobs:
  create-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create Azure VM
      run: |
        az vm create \
          --resource-group borra \
          --name myVM \
          --image Win2019Datacenter \
          --admin-username azureuser \
          --admin-password Passw0rd1234 \
          --size Standard_DS1_v2
